apiVersion: v1
kind: Pod
metadata:
  name: podspoon8
  labels:
    purpose: demo-spoon-job
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
  - name: demo-spoon-job
    image: cmolaro/spoon:v1.5
    command: ["/entrypoint.sh"]
    args: ["runt","sample/dummy.ktr"]
    volumeMounts:
      - mountPath: "/jobs"
        name: task-pv-storage
  restartPolicy: OnFailure
